name: Latest hashnode blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-hashnde-blog:
    name: Update this repo's README with the latest hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: itsvinayak/blog-post-workflow@master
        with:
          feed_list: "https://itsvinayak.hashnode.dev/rss.xml"
